name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET (v8.0)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'

      - name: Restore
        run: dotnet restore
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

      - name: Build & test (.NET v8.0)
        run: dotnet test --configuration Release --logger GitHubActions
